### ISSUE TITLE
Taking over this crate

### ISSUE THREAD

**Issue by dflemstr** [rust-bridge/v8-sys#2]
Hey @steveklabnik, I sent you an email but it might have landed in spam.  I'd like to take over `v8-sys` on crates.io and publish this crate: https://github.com/dflemstr/v8-rs/tree/master/v8-sys. Seeing as this library is basically "hello, bindings world," would that be possible?

**Comment by steveklabnik** [comment]
I did, sorry, there's rustconf and rustfest, so I've been bad at email. I'm happy to, but it might take me until tomorrow. Sorry!

**Comment by dflemstr** [comment]
@steveklabnik friendly reminder in case you forgot :)
